### ISSUE TITLE
Možnost darů skrze aplikaci - FE

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono#342]
[figma](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=14216%3A261578)

Acceptance Criteria:
- in-app notifikace:
   - generovana na strane FE (per device, ne account)
   - notifikace zakryva celou aplikaci
   - zobrazovat se bude po min 14 dnech (pocitano od prvniho spusteni aplikace a pak po poslednim zobrazeni, ihned po otevreni aplikace)
   - neprihlasenym uzivatelum neumoznujeme vypnout notifikace
   - aplikace si pamatuje nastaveni notifikaci per user prihlaseny na device
   - po kliknuti na tlacitko Chci prispet se zobrazi prohlizec ([link](https://www.darujme.cz/projekt/1206713), vratime se na main screen/login page)
   - notifikace se daji vypnout v uprave profilu (defaultne zapnuto)
   - "Upravit nastaveni notifikaci" je link button - po kliknutí se zobrazi Account
- rozsireni/zmena zobrazeni accountu 
   - skryt tlacitko Co s body 
   - preskupeni tlacitek/textu viz figma
   - pridat text a tlacitko Chci prispet ([link](https://www.darujme.cz/projekt/1206713), vratime se do zobrazeni accountu)
   - rozdeleni upravy accountu na osobni udaje a notifkace
   - v ramci teto story umoznime vypnout/zapnouit jen notifikace pro Darujme, ostatni neresime

Related to task: https://github.com/Loono-cz/loono-tasks/issues/32

**Comment by jana-pajdlhauserova** [comment]
Aktualizovaný link na Figmu - https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15069%3A261264

**Comment by KeiShadow** [comment]
Zde se čeká na dodání ilustračního obrázku od @jana-pajdlhauserova

**Comment by jana-pajdlhauserova** [comment]
@KeiShadow Ilustracia doplnena do navrhu vo Figme - viz https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15069%3A261264

**Comment by KeiShadow** [comment]
Nova verze by zachvili mela byt na testflightu.

**Comment by jana-pajdlhauserova** [comment]
Otestovane - interakcie a flows ok. 

Visual stuff to be fixed:

1. Notifikace - texty by mali byť zarovnané na stred. Ak je to možné tak by bolo fajn ešte trochu zväčšiť margin medzi tlačítkom a textom v spodnej časti obrazovky.
2. User account - zväčšiť margin medzi tlačítkami.
3. Nastavení notifikací - v rozbalenom stave sa v hornej a spodnej časti accordionu zobrazuje tenká čiara.

**Comment by Deli-Sedlackova** [comment]
Za mě vše sedí, prosím jen v poslední větě v In-app notifikaci přidat čárku: "Pokud si přeješ tuto zprávu více nezobrazovat, **můžeš si upravit nastavení notifikací.** "

**Comment by JanaHej** [comment]
Za me ok

**Comment by Brambora0** [comment]
@Deli-Sedlackova čárku jsem přidal

**Comment by KeiShadow** [comment]
je to na PR.

**Comment by jana-pajdlhauserova** [comment]
Otestovane - ok.
