### ISSUE TITLE
Přidání samovyšetření kůže - FE

### ISSUE THREAD

**Issue by JanaHej** [Loono-cz/loono#343]
Related to task https://github.com/Loono-cz/loono-tasks/issues/50

samovysetreni je razeno podle data (jako prvni je samovysetreni, ktere drive zmizi)

**Comment by janblahacgi** [comment]
Chybí oprava testů.

**Comment by Deli-Sedlackova** [comment]
Při testování jsem narazila na pár věcí: 
1) při rozkliku progress baru se zobrazí badge, nicméně místo nárameníku jsou zde uvedené štíty. Je potřeba změnit jak obrázky badgů (na nárameníky) tak textaci: Za každé samovyšetření získáš v základu 50 Loono bodů. Za každé třetí samovyšetření dostaneš nové nárameníky. 
2) Na kartě samovyšetření a v detailu Jak se vyšetřit je v patičce textace "Více informací o správném postupu samovyšetření nalezneš také na našem webu nebo na webu České onkologické společnosti." Odkazy zde ale vedou na samovyšetření varlat. Je potřeba je změnit na:  
pro Loono web: [https://www.loono.cz/prevence/kuze#kuze](url)
pro Českou onko společnost: [https://www.linkos.cz/pacient-a-rodina/onkologicke-diagnozy/maligni-melanom-spinaliom-bazaliom-c43-44-d03/maligni-melanom-a-ostatni-nadory-kuze/](url)


![Image](https://user-images.githubusercontent.com/98404015/189299399-d964fde5-f469-4586-9910-b3ecf03ebdc9.png)



![Image](https://user-images.githubusercontent.com/98404015/189299509-41faf52f-b9af-492f-89c8-3e4da547c7a0.png)



![Image](https://user-images.githubusercontent.com/98404015/189299562-e2ee4fdb-dc92-43ca-84a4-cfceeed2695d.png)



![Image](https://user-images.githubusercontent.com/98404015/189299611-da6fd829-0bed-43fb-a46b-948dfd5dc8fe.png)



![Image](https://user-images.githubusercontent.com/98404015/189299645-566777d8-cd6b-43d5-a268-12491cf42276.png)

**Comment by Deli-Sedlackova** [comment]
Samovyšetření prsou/varlat i kůže zůstává v kolonce "Vyšetři se" pouze 3 dny včetně kalendářního dne, na které vychází samovyšetření po měsíci (když vychází na 6.9., zůstává v kolonce pouze do 8.9.). Žádoucí chování je, aby v kolonce "Vyšetři se" samovyšetření zůstávalo 3 dny ke kaldnářnímu dni, tedy když samovyšetření vychází na 6.9., aby mi zůstalo v kolonce do 9.9.

**Comment by Brambora0** [comment]
U samovyšetření kůže chybí badge (asset) pro nezískané nárameníky (disabled).

**Comment by KeiShadow** [comment]
@Brambora0  Ikonku ti udelam klidne to nebude problem :) mrkni se mezitim proc ti padaji testy.

**Comment by KeiShadow** [comment]
@Brambora0 uz je to hotove ? Jestli ano tak mi pisni, hodim to do masteru at se to muze otestovat :)

**Comment by Brambora0** [comment]
@KeiShadow ano

**Comment by KeiShadow** [comment]
Nova verze je na TS.
@jana-pajdlhauserova , @JanaHej , @Deli-Sedlackova

**Comment by Deli-Sedlackova** [comment]
@Brambora0 @KeiShadow  za mě už v pořádku, včetně žádoucího chování při řazení do "vyšetři se" kolonky. Jediné co, tak bych prosila opravit překlepy - chybí mezery při odkazech na web loono a českou onkologickou společnost v patičce. Toto chybí jak v detailu karty samovyšetření, tak pod videonávodem: 


![Image](https://user-images.githubusercontent.com/98404015/191737633-78b542dc-4354-4eb7-be4f-0ea986ee2f26.jpeg)
![Image](https://user-images.githubusercontent.com/98404015/191737632-a6beee85-2830-42d4-8921-634d6c1344ac.jpeg)

**Comment by KeiShadow** [comment]
Je to na pull requestu.
