### ISSUE TITLE
Vlastní prohlídky - Přidat prohlídku - FE

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#353]
[Figma - sekce Pridani vlastni prohlidky](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=14723%3A282829)

Poznamky:
- na main scren pridan floating button, viz figma
- omezeni poctu vlastnich prohlidek na 10 - jedna se o omezeni prohlidek, ne konkretnich navstev, tj. u pravidelnych prohlidek pridavame dalsi prohlidky bez omezeni
- Ciselniky specialista - seznam razen abecedne, bez moznosti vyhledavani
- seznam specialistů [ZDE](https://docs.google.com/spreadsheets/d/1mzABhp0fzzCAjIXmfzfDnVkYYUYKsSH5BMuKSefo1Vs/edit?usp=sharing)
- u jednorazove prohlidky:
   - datum povinny, jen v budoucnu (lze zadat i dnesni datum s casem v budoucnu)
   - poznamka je nepovinna, velikost poznamky max 256 znaku
 - u pravidelne prohlidky
   - interval povinny (min 6 mesicu, max 10 let)
   - povinny vyber datumu posledni navstevy nebo zadani "Nevim". Pokud uzivatel zada Nevim, ulozime status Unknown bez datumu. Uzivateli se pak prohlidka objevi v sekci "Objednej se".
   - datum navstevy lze zadat jen v budoucnu (lze zadat i dnesni datum s casem v budoucnu). Uzivatel musi zadat datum, nebo zaskrtnout Nevim. Pokud uzivatel zada datum, aplikace si ulozi 2 navstevy (prvni s datem posledni navstevy nebo stavem unknown, druhou s datumem v budoucnu a stavem new). Pokud uzivatel datum navstevy nezada, aplikace ulozi jen posledni prohlidku.
   - poznamka je nepovinna, velikost poznamky max 256 znaku
   - poznamku lze zadat jen v pripade, ze uzivatel zadal datum navstevy (poznamka se tyka konkretni navstevy). Jinak je pole neaktivni.

**Comment by janblahacgi** [comment]
Ladí se intervaly vyšetření.

**Comment by jana-pajdlhauserova** [comment]
Testing findings

Functional stuff to be fixed:

- [ ] Po výbere specialistu sa nasledujúci select box pre vyber typu vyšetření zobrazuje v error state/required field - malo by vyzerať ako ostatné nevyplnené select boxy.
- [ ] Overlay - Výber termínu vyšetření – nastaviť východzie nastavenie dátumu na aktuálny dátum
- [ ] Overlay - Výber termínu vyšetření - výber času vyšetření (2. krok) - ikonka „Close overlay“ vracia o krok späť – overlay by sa mal zabaliť
- [ ] Výber termínu vyšetření - keď som zvolila čas objednání 22:05 alebo 22:25 v input fielde sa následne zobrazil čas 22:03/22:06 (korešpondovalo s aktuálnym časom) + pole sa zobrazilo v error state. 
- [ ] Poznámka k návšteve - pri zaškrtnutí checkboxu "Zatím nevím" by malo byť pole pre poznámku disabled. V pripade, že som najprv vyplnila dátum a následne zaškrtla "Zatím nevím" pole pre poznámku ostalo aktívne.   
- [ ] Pri jednorazovej prohlídke by nemalo byť možné prohlídku uložiť bez zadania termínu vyšetření - chybí validace
- [ ] Pri nekompletnom vyplnení formulára sa po kliknutí na tlačítko "Uložit" zobrazia v error state aj vyplnené polia - mali by sa zvýraznit len povinné polia, ktoré nie sú vyplnené.

Visual stuff to be fixed:

- [ ] Select boxy - upravit ikonu - namiesto šipky by mal byť chevron + ikona select boxu, ktorý bol rozkliknutý ako posledný má inú farbu/je zvýraznená - mala by mať default farbu ako ostatné neaktívne select boxy.
- [ ] Medzi toggle buttons pre výber frekvencie prohlídky a termínom vyšetření chýba divider/čiara.
- [ ] Field "Příští vyšetření" - zmenšiť spacing medzi ikonou a datumom (prípadne zväčšiť celé pole), tak aby bol viditeľný dátum aj čas prohlídky.
- [ ] Fields "Poslední vyšetření" a "Příští vyšetření" - floating labels sú zarovnané inak ako v prípade ostatných polí.
- [ ] Fields "Poslední vyšetření" a "Příští vyšetření" - zväčšiť spacing medzi date pickerom a checkboxom
- [ ] Poznámka k návšteve - placeholder text by mal byť vertikálne zarovnaný zhora, nie na stred 
- [ ] Poznámka k návšteve - placeholder text by mal mať rovnakú veľkosť ako ostatné placeholder texty (14 px)
- [ ] Poznámka k návšteve - v prípade, že je pole aktívne, outline color by mala byť #BE5713
- [ ] Overlays pre výber specialistu, typu vyšetření by sa mali vysúvať zospodu - rovnako ako overlays v detaile prohlídky (pri úprave termínu prohlídky apod.) 
- [ ] Overlay - Vyber typu vyšetření - pod select boxami sa zobrazuje šedý box
- [ ] Overlay - Vyber frekvence vysetreni - picker posunúť vyššie resp. východziu hodnotu nastaviť na 9 mesiacov + zväčšiť spacing medzi oranžovou tečkou a textom "Jednou za"
- [ ] Overlays - Výber termínu vyšetření a Výber termínu posledního vyšetťení - zmenšit počet viditeĺných hodnôt v pickeri tak ako je to v prípade ostatných pickerov (napr. pri úprave termínu v detaile prohlídky) - viditeľných je 5 hodnôt a ďalšie dve hodnoty sú vditeľné len čiastočne. 
- [ ] Overlay - Výber termínu vyšetření - výber času vyšetření (2. krok) - v headeri by namiesto chevronu mala byť ikona šipky
- [ ] Overlay - Výber termínu vyšetření - výber času vyšetření (2. krok) - zväčšiť spacing medzi tlačítkom "Pokračovat" a text fieldom s původným termínom vyšetrenia
- [ ] Doladit spacing medzi jednotlivým poliami vo formulári

**Comment by KeiShadow** [comment]
Opraveno v pristim updatu.

**Comment by Deli-Sedlackova** [comment]
@KeiShadow 
Bugs to be fixed:

- [ ] nefunguje přidání druhé vlastní prohlídky u Zubaře - píše, že se "něco nepovedlo"



https://user-images.githubusercontent.com/98404015/194561841-4842fc16-c4b5-475e-955a-9287c6647bce.MP4


- [ ] při přidání poznámky k vlastní prohlídce se objeví chybová hláška, že není připojení k internetu (viz klip)

https://user-images.githubusercontent.com/98404015/194561621-4edc2c61-1b9a-4c0f-b8f1-b35b19d44299.MP4

- [ ] v rozkliku detailu prohlídky se nezobrazuje uvedená poznámka
- [ ] v seznamu specialistů jsou duplicity: Kožař, Očař, Urolog(Urologie)
- [ ] v typu vyšetření je zvláštní čára dole viz screenshot: 

![Image](https://user-images.githubusercontent.com/98404015/194562075-f0c1b3b0-4838-46dd-b2ab-747c56b09d24.PNG)

**Comment by JanaHej** [comment]
- [ ] pokud zadam datum na formulari a pak zaskrtnu nevim, datum se nesmaze, ani nelze manuane smazat

**Comment by KeiShadow** [comment]
nefunguje přidání druhé vlastní prohlídky u Zubaře - píše, že se "něco nepovedlo":
Tohle mohlo zapricinit, ze slo pridat vice nez 10 prohlidek, pokud je vice nez 10 prohlidek tak jsem nechal tlacitko zesednout a nejde na nej kliknout.

v rozkliku detailu prohlídky se nezobrazuje uvedená poznámka:
Opraveno.

Při přidání poznámky k vlastní prohlídce se objeví chybová hláška, že není připojení k internetu (viz klip):
tohle by chtelo projit znovu, nejak se mi ta chyba nepodarila odchytit.

pokud zadam datum na formulari a pak zaskrtnu nevim, datum se nesmaze, ani nelze manuane smazat
Opraveno, text zesedne dle navrhu ve Figme.

v typu vyšetření je zvláštní čára dole viz screenshot:
Opraveno.

**Comment by JanaHej** [comment]
Datum uz se zneaktivni, ale pri zaskrtnuti/odskrtnuti checkboxu se neulozi nevim, ale datum, viz video

https://user-images.githubusercontent.com/101713252/194698750-80e180e5-8688-4a7a-b590-ce92073342df.mp4

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.302
Bugs to be fixed: 

LOW
- [ ] v typu vyšetření je stále zvláštní čára dole viz screenshot

**Comment by JanaHej** [comment]
Poznamka se zobrazuje i kdyz neni prohlidka u pravidelnych, kdyz se vytvori nova, tak ji neprepise. Tohle mame reportovane?![image](https://user-images.githubusercontent.com/101713252/194704871-32063a52-56e7-4aa9-b391-61be29bbf422.jpeg)

**Comment by JanaHej** [comment]
- [ ]  Body u vlastnich - dostanou hned po vytvoreni, i kdyz neni datum posledni navstevy (plus ten blocek se spatne jmenuje - body za preventivni prohlidky)

verze 02.302

**Comment by KeiShadow** [comment]
Datum uz se zneaktivni, ale pri zaskrtnuti/odskrtnuti checkboxu se neulozi nevim, ale datum, viz video 
Zde mazu datum v pripade kdy uzivatel zaskrne Nevim nebo Jeste nevim

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.306 za mě už vše ok

**Comment by JanaHej** [comment]
02.306

- [ ] body se pricitaji po zadani vlastni pravidlene prohlidky i kdyz dal datum posledni navstevy Nevim (zobrazi se az po opetovnem prihlaseni)

**Comment by jana-pajdlhauserova** [comment]
Verzia 02.306

HIGH

- [ ] Pri vybere casu sa vybrany cas obcas posunie o 5 minut oproti aktualnemu vyberu - viz [video ](https://loonocz.slack.com/files/U03MAC2DP98/F046HTFRLV6/97cb208f-648b-4335-a342-f8d6d2a4d92e.mp4). Nedeje sa to ale zakazdym - zatial som nenasla jasny pattern, ale pride mi, ze to nejako suvisi s time pickerom a jeho previazanostou s aktualnym casom na zariadeni (aktualny cas je 13:51, v time pickeri zvolim cas vysetreni 13:50 a automaticky mi to nastavi vybrany cas na 13:55, zvoleny datum je 10.11.2022).

**Comment by jana-pajdlhauserova** [comment]
Verze 0.2.309

LOW

- [ ] Zväčšiť prosím spacing medzi toggle buttonom a nasledujúcim inputom - viz https://drive.google.com/file/d/1v24WAgWNyAp4_0l3v4vd_UfXKEHmrog_/view?usp=sharing. Spacing by mal byť rovnaký ako spacing medzi ostatnými input fieldmi.
