### ISSUE TITLE
Vlastní prohlídky - detail - FE

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#354]
Figma:
- [Vlastni prohlida_Pravidelna - detail](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15002%3A281323)
- [Vlastni prohlida_Jednorazova - detail](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15011%3A278043)

Poznámky:

Detail vlastní prohlídky by měl být stejný jako u povinné prohlídky. 
Neplatí pro: 
1. Box s info o odměnách za prohlídky - zobrazuje se pouze u pravidelných prohlídek (vlastních i povinných - obsah boxu se liší); 
2. Sekce s FAQ - zobrazuje se pouze u povinných prohlídek); 
3. Progress bar - zobrazuje se pouze u pravidelných prohlídek (vlastních i povinných) - logika zobrazení je stejná

Header
- Přidat ikonu tři tečky pro zobrazení dalších akcí (pravidelné vlastní prohlídky - akce "Upravit prohlídku", "Smazat prohlídku" a "Zpět"; jednorazové vlastní prohlídky - pouze akce "Smazat prohlídku" a "Zpět")

Hlavička prohlídky:
- pridat typ prohlídky 
- u frekvence prohlídky a termínu poslední prohlídky jsou nové ikony
- Ikona specialistu - v prípade pridania vlastnej prehliadky u specialisty u ktorého existuje aj default/povinná prohlídka, použije sa rovnaká ikona ako v príde default prohlídky. V prípade pridania vlastnej prehliadky u specialistu u ktorého neexistuje default/povinná prehliadka, použije sa univerzálne ikona specialistu.

Poznámka k návštěvě
- zobrazí se pouze u prohlídek se zadaným termínem

Do spodní části přidat sekci "Další prohlídky u specialisty (zobrazí se karty prohlídek, které mají stejný typ specialisty) - řazení karet - dle data prohlídky

**Comment by Deli-Sedlackova** [comment]
@KeiShadow 
Bugs to be fixed: 
- při přidání poznámky k vlastní prohlídce se objeví chybová hláška, že není připojení k internetu
- v rozkliku detailu prohlídky se nezobrazuje uvedená poznámka

**Comment by JanaHej** [comment]
- [ ] progrs bar obsahuje slovo Preventivni prohlidka
- [ ] souvisejici prohlidky obcas obsahuji spatna data (zxrejme i cancellovane prohlidky)

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.305
HIGH

- [ ] nelze potvrdit absolvovanou prohlídku, viz klip


https://user-images.githubusercontent.com/98404015/194749658-288ab515-ac31-49e0-bceb-fc716f15bcbe.MP4

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.306 
HIGH

- [ ] Stále tam mám prohlídku, která mi měla přes noc zmizet (jednorázová vlastní z 8.10.2022)

**Comment by JanaHej** [comment]
02.306
- [ ] - [ ] Upravit termin u vlastni prohlidky nelze do minulosti - zobrazi se neco se nepovedlo, misto nelze zadat datum v minulosti (plati u hodin, u dnu to funguje spravne

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.307

- [ ] Divné chování v případě, že chci rozkliknout související prohlídky. Buďto se mi zobrazí "Něco se nepovedlo" nebo aplikace vůbec nereaguje, viz klipy

https://user-images.githubusercontent.com/98404015/195126011-95fdf3a1-740f-4d96-8b00-45edbc5030ee.MP4



https://user-images.githubusercontent.com/98404015/195126021-63d22b88-99b6-4497-afd1-9a03d9af0986.MP4
