### ISSUE TITLE
Vlastní prohlídky - upravit prohlídku - FE

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#355]
**1. Úprava prohlídky**

Upravuje se z detailu prohlídky kliknutím na ikonu tři tečky - následne se zobrazí menu s možnými akcemi.

- U pravidelnych vlastnich prohlídek - v menu se zobrazí akce "Upravit prohlidku" (zmenit interval prohlidky a termín posledního vyšetžení), "Smazat prohlidku" a "Zpět".
- U jednorazovych vlastnich prohlídek - v menu se zobrazí akce pouze "Smazat prohlidku" a "Zpět".

Figma:
- [Vlastni prohlidka_Uprava prohlidky](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=14439%3A263602)
- [Vlastni prohlidka_Smazani prohlidky](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=14455%3A264131)

**2. Úprava termínu prohlídky**

Úpravuje se přes tlačítko "Upravit termín" (původní label na tlačítku byl "Upravit datum" - je potřeba změnit) - následne se zobrazí menu s možnými akcemi.

- U pravidelnych vlastnich prohlídek - v menu se zobrazí akce "Změnit datum", "Zrušit termín" a "Zpět".
- U jednorazovych vlastnich prohlídek - nezobrazuje se menu, ale rovno sa zobrazí overlay pre úpravu termínu.

Figma:
- [Vlastni prohlidka_Uprava terminu prohlidky](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15139%3A265385)

**Comment by KeiShadow** [comment]
TODO: Na BE porad nejde mazat prohlidky.

**Comment by Deli-Sedlackova** [comment]
@KeiShadow 
Bugs to be fixed: 

- [ ] při přidání poznámky k vlastní prohlídce se objeví chybová hláška, že není připojení k internetu
- [ ] nelze upravit termín přidané vlastní prohlídky - přijde validace, že ještě není čas se objednat. Při úpravě 2 roky od stávajícího termínu to aplikace vezme a termín se uloží. (viz první klip)
- [ ] v detailu prohlídky se ukládá jiné datum, než požadované (zadávám 8.12.2022 a aplikace si ukládá 7.12.2022) - prohlídka se následně ani neuloží (viz druhý klip)

https://user-images.githubusercontent.com/98404015/194560381-ae5141a3-fb27-4e3a-9f58-79c4a9fbb2ff.MP4


https://user-images.githubusercontent.com/98404015/194560659-3a7834b7-700e-41df-800f-3b50d42c662f.MP4

**Comment by JanaHej** [comment]
- [ ] divna hlaska neni mozne zadat prohlidku

verze 02.302



https://user-images.githubusercontent.com/101713252/194705131-37b6bb21-c1eb-4647-8a9d-76245be4a87e.MP4

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.303

HIGH

- [ ] nelze upravit termín první  prohlídky, přijde hláška, že se "neco nepovedlo" a prohlídka se neuloží



https://user-images.githubusercontent.com/98404015/194720468-2dab6866-b620-4bb4-bc1d-77ade2535a0a.MP4

**Comment by KeiShadow** [comment]
při přidání poznámky k vlastní prohlídce se objeví chybová hláška, že není připojení k internetu:
nedokazal jsem odchytit chybu.

**Comment by JanaHej** [comment]
- [ ] poznamka je poradd neovladatelna (nelze zavrit klavesnici pro psani, prekryva tlacitko) - ocekavane chovani je podobne jako ve formulari pro feedback


https://user-images.githubusercontent.com/101713252/194744723-98cff348-54e3-4273-a890-0f56bc3f4f81.mp4



verce 02.305

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.305
HIGH

- [ ] nelze upravit prohlídku, ať už úpravou termínu (přijde validace, že datum prohlídky musí být v budoucnu) nebo skrze tři tečky nahoře, appka napíše, že se "něco nepovedlo" viz klip


https://user-images.githubusercontent.com/98404015/194751020-1181a0b2-4b17-465c-95d8-76fef44f4b5c.MP4

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.306
za mě už vše ok

**Comment by jana-pajdlhauserova** [comment]
Verze 0.2.306

MEDIUM

- [ ] Nesprávny label akce v menu pod tři tečky v detaile jednorazovej i pravidelnej vlastnej prehliadky. Namiesto „Zrušit prohlídku“ by malo by byť „Smazat prohlídku“
- [ ] Label na tlačítku v potvrdzujúcom overlay pri smazani prohlidky by mal byť „Smazat prohlídku“. 
- [ ] Text v snack bare potvrdzujucom smazani prohlidky by mal byť „Prohlídka byla smazána.“

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.307
MEDIUM

- [ ] Divné chování při zadání a úpravě termínů prohlídky. Zadám prohlídku v onboardingu, upravím termín poslední prohlídky (nový termín prohlídky nemám) a progress bar ukazuje jiný stav prohlídky. Následně po přidání termínu prohlídky progress bar ukazuje správně. Po zrušení termínu je to opět rozházené. Viz klip:


https://user-images.githubusercontent.com/98404015/195129829-74b8652a-15d1-46ef-852b-e8a9205b2418.MP4
