### ISSUE TITLE
Vlastní prohlídky - Main screen - FE

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#357]
Figma:
- [Prevence Home](https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=14530%3A267589) a související.

Notes:
- Na hlavní stránce odstranit na kartách prohlídek v sekcích "Připoneme ti objednání" a "Připomeneme ti prohlídku" indikátor progress baru.
- U vsech karet (povinne i vlastni prohlidka) pribyde typ prohlidky (napr Kontrola). Pro povinne preventivni prohlidky zobrazime text "Preventivní prohlídka", u ostatnich to, co uzivatel zadal. Stylování a všechny stavy karet viz https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15360%3A268976
- TODO dodat ikonu lekare 
- Přidat na konec seznamu karet prohlídek "card placeholder" s info o tom, kolik vlastních prohlídek si uživatel ještě může přidat.
- Řazení karet vychazi z puvodniho nastaveni, viz [wiki](https://github.com/Loono-cz/loono-tasks/wiki/LOON-324-----Main-screen---overview)
   - V sekci BEZ NA PROHLIDKU - radime podle datumu - od nejblizsiho termínu (date, time). Pokud by byly dve a vice prohlidek se stejnym casem, radime nejdrive povinne prohlidky (podle priority) a pak vlastni (abecedne).
   - V sekci OBJEDNEJ SE se nejdrive seradi prohlídky, které jsou v okně 2 měsíců pro včasné objednání (razeno primarne podle data a sekundarne podle priority u povinnych prohlidek, za nimi abecedne vlastni prohlidky. Za nimi nasleduji prohlidky po terminu vcasneho objednani, serazeni podle priority (povinne) a pak abecedne vlastni prohlidky. TODO overit v kodu
   - DALŠÍ PROHLÍDKY - tato sekce by mela byt beze zmen (vlastni prohlidky zde nejsou)
   - PŘIPOMENEME TI PROHLÍDKU - razeno podle data a sekundarne podle priority(povinne prohlidky) a za nimi abecedne vlastni.
   - PŘIPOMENEME TI OBJEDNÁNÍ - razeno podle data a sekundarne podle priority(povinne prohlidky) a za nimi abecedne vlastni.

**Comment by jana-pajdlhauserova** [comment]
Testing findings

Functional stuff to be fixed:

- [ ] Na konci seznamu prohlídek chýba "card placeholder" s info o tom, kolik vlastních prohlídek si uživatel ještě může přidat.
- [ ] Pravidelná vlastní prohlídka vytvorená bez zadania termínu příštího vyšetření a bez zadania termínu posledního vyšetření sa v zozname prohlídek zaradila medzi "Další prohlídky" - mala by sa zaradiť do sekcie "Objednej se".
- [ ] Na kartách povinných prohlídek je uvedený nesprávny typ vyšetření - malo by tam byť "Preventivní prohlídka".

Visual stuff to be fixed:

- [ ] Floating button by mal mať farbu #BE5713 (primary color)
- [ ] Karta prohlídky - info o bodech by sa malo zobrazit v spodnej časti karty bez ohľadu na to o aký typ prehliadky ide.
- [ ] Ikony lekarov by mali byt zarovnane so spodným okrajom karty
- [ ] Doladit stylovani karet - zväčšiť spacing medzi typem specialistu, typem vyšetření a termínem vyšetření.

**Comment by Deli-Sedlackova** [comment]
Bugs to be fixed: 
- při vyčerpání 10 prohlídek je sice dole napsáno, že je seznam prohlídek plný, ale prohlídky lze i nadále přidávat

**Comment by JanaHej** [comment]
- [ ] u existujich uzivatelu nevidime mandatory prohlidky (praktik, zubar ...)

**Comment by KeiShadow** [comment]
při vyčerpání 10 prohlídek je sice dole napsáno, že je seznam prohlídek plný, ale prohlídky lze i nadále přidávat opraveno v https://github.com/Loono-cz/loono/issues/353

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.302
Bugs to be fixed:
HIGH
- [ ] při vyčerpání 10 prohlídek je sice dole napsáno, že je seznam prohlídek plný, ale prohlídky lze i nadále přidávat, poté co vyplním prohlídku, tak se mi ale napíše "Něco se nepovedlo" (viz klip). Při vyčerpání 10 prohlídek by se spíš mělo tlačítko zneaktivnit. Takto je to pro uživatele celkem nepříjemné, když si nevšimne popisku dole.

https://user-images.githubusercontent.com/98404015/194699392-3aaf19e6-e216-4cfe-a650-e69980f4ca95.MP4

**Comment by Deli-Sedlackova** [comment]
@KeiShadow Verze 0.2.303
Bugs to be fixed:
HIGH
- [ ] při vyčerpání 10 prohlídek je sice dole napsáno, že je seznam prohlídek plný, ale prohlídky lze i nadále přidávat, poté co vyplním prohlídku, tak se mi ale napíše "Něco se nepovedlo" (viz klip). Při vyčerpání 10 prohlídek by se spíš mělo tlačítko zneaktivnit. Takto je to pro uživatele celkem nepříjemné, když si nevšimne popisku dole. Stále se mi to chová stejně, tlačítko na přidání se nezneaktivňuje, viz klip:


https://user-images.githubusercontent.com/98404015/194720927-e1c9d723-dfac-47ac-8017-72078722c86a.MP4

**Comment by JanaHej** [comment]
- [ ] Dalsi vec divne se zobrazuje cas na main screen vs detail, je tam obcas rozdil 2 hodin (ne vzdy)

verze 02.305



https://user-images.githubusercontent.com/101713252/194744655-4be30f4d-205a-4666-9ea7-50035805f94b.mp4

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.305

HIGH

- [ ] prohlídka se řadí do nesprávných "chlívků":
V sekci BEZ NA PROHLIDKU - radime podle data chronologicky - od nejblizsiho termínu (date, time). Pokud by byly dve a vice prohlidek se stejnym casem, radime nejdrive povinne prohlidky (podle priority) a pak vlastni (abecedne).
V sekci OBJEDNEJ SE se nejdrive seradi prohlídky, které jsou v okně 2 měsíců pro včasné objednání (razeno primarne podle data a sekundarne podle priority u povinnych prohlidek, za nimi abecedne vlastni prohlidky. Za nimi nasleduji prohlidky po terminu vcasneho objednani, serazeni podle priority (povinne) a pak abecedne vlastni prohlidky.
DALŠÍ PROHLÍDKY - tato sekce by mela byt beze zmen (vlastni prohlidky zde nejsou)
PŘIPOMENEME TI PROHLÍDKU - razeno podle data chronologicky, a sekundarne podle priority nejdříve (povinne prohlidky) a za nimi abecedne vlastni.
PŘIPOMENEME TI OBJEDNÁNÍ - razeno podle data chronologicky, a sekundarne podle priority nejdříve (povinne prohlidky) a za nimi abecedne vlastni.

Toto nesedí, viz klip: 

https://user-images.githubusercontent.com/98404015/194750672-27203aad-9359-4244-9ce8-36848da18561.MP4

**Comment by JanaHej** [comment]
02.306

- [ ] u noveho cloveka, projdu onboarding dostanu se na main screen. Mam v sekci Dalsi prohlidky Kozare, nez projdu onboardingem, tak si jeste vytvorim vlastni jednorazovou prohlidku Kozar. Pak se dostanu do divne smycky viz video. Pomuze odhlaseni/prihlaseni



https://user-images.githubusercontent.com/101713252/194785085-7ff13b15-f361-4e9b-a3d1-1f8a872387bc.MP4

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.307

- [ ] řazení prohlídek na main screen je stále neopravené, viz můj koment výše
