### ISSUE TITLE
Přidání logo CGI na splash screen

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#372]

**Comment by Deli-Sedlackova** [comment]
Prosím o aktualizaci jak úvodní Splash screen, tak pro navracející se uživatele. Jedná se o přidání loga CGI s textací, jak je uvedeno ve Figmě: [https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=15638%3A862926]

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.305
HIGH
Splash screen se mi při opakované návštěve (stávající uživatel) zobrazuje zvláštně., na chvíli se zobrazí původní a následně nová. Čas je natolik krátký, že jsem si ani nevšimla, co je tam textově. viz klip:


https://user-images.githubusercontent.com/98404015/194747384-0518fad9-5620-41d9-8a07-14f8d00c2a59.MP4

**Comment by Brambora0** [comment]
Splashscreen se zobrazuje, tak dlouho, jak se aplilace načítá

**Comment by Deli-Sedlackova** [comment]
Rozumím, ale takhle jak tam jsou vlastně 2 splashscreeny, tak je pro mě nečitelné, co na ní je.

**Comment by Deli-Sedlackova** [comment]
Verze 0.2.306 
HIGH

- [ ] stále jsou při opětovném otevření aplikace 2 splash screen, původní a nová viz výše
