### ISSUE TITLE
FE Formulář - Dotaz do odborné poradny

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#467]
https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=16867%3A174786&t=JTGoQjI6jzFq5fX4-0

AC:
- Je nutné vybrat pouze jednu z nabízených oblastí/topiků dotazu (batch).
- Existuje pole pro zadání textu dotazu s omezením na max 700 znaků.
- Spolu s dotazem jsou odesílány také: jméno, pohlaví, věk, kontaktní email.
- Existují validace na povinnost polí oblast a text dotazu.
- Po odeslání je uživatel přesměrován na hlavní obrazovku.

**Comment by smolikjacgi** [comment]
0.2.329
