### ISSUE TITLE
FE Vyvolání formuláře poradny

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono#468]
Formulář je možné otevřít:
- Hlavní obrazovka na konci (https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=16858%3A155886&t=JTGoQjI6jzFq5fX4-0)
- Pravidelná prohlídka, na konec sekce Časté dotazy (https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=16858%3A154261&t=JTGoQjI6jzFq5fX4-0)
- V rámci samovyšetření, na konci častých dotazů (https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=16867%3A173776&t=JTGoQjI6jzFq5fX4-0)
- Udržovat kontext? (možnost předat formuláři informace, např. požadovaný výběr oblasti/topiku)

**Comment by jana-pajdlhauserova** [comment]
@smolikja Myslím, že sme sa nakoniec dohodli, že to nebudeme komplikovať a tagy nebudú predvolené. 
@janblahacgi Pamätám si to správne?

Ešte prosím o pridanie karty pre preklik na formulár do detailu vlastnej prohlídky (pravidelnej i jednorazovej) - viz https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=17163%3A164262&t=nKoHMWfBWUryxNd4-1 a https://www.figma.com/file/E3BhDWp6O8d1XmsbC46mcr/Loono?node-id=17163%3A164115&t=nKoHMWfBWUryxNd4-1

**Comment by jana-pajdlhauserova** [comment]
@smolikjacgi Tagy by mali byť predvolené nasaledovne:

- Preklik z main screen - predvolený tag “Preventivní prohlídky a screeningy”
- Preklik z detailu prohlídky (povinné i vlastní) - predvolený tag “Preventivní prohlídky a screeningy”
- Preklik z detailu samovyšetření - predvolený tag “Samovyšetření prsou/varlat”

**Comment by smolikjacgi** [comment]
0.2.329
